AtlasSolar/Controllers/SPPStatusesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AtlasSolar.Models;
using PagedList;

namespace AtlasSolar.Controllers
{
    public class SPPStatusesController : Controller
    {
        private NpgsqlContext db = new NpgsqlContext();

        // GET: SPPStatuses
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Index(string SortOrder, string NameEN, string NameKZ, string NameRU, int? Page)
        {
            var sppstatuses = db.SPPStatus
                .Where(m => true);
            
            ViewBag.NameENFilter = NameEN;
            ViewBag.NameKZFilter = NameKZ;
            ViewBag.NameRUFilter = NameRU;
            
            ViewBag.NameENSort = SortOrder == "NameEN" ? "NameENDesc" : "NameEN";
            ViewBag.NameKZSort = SortOrder == "NameKZ" ? "NameKZDesc" : "NameKZ";
            ViewBag.NameRUSort = SortOrder == "NameRU" ? "NameRUDesc" : "NameRU";

            if (!string.IsNullOrEmpty(NameEN))
            {
                sppstatuses = sppstatuses.Where(s => s.NameEN.ToLower().Contains(NameEN.ToLower()));
            }
            if (!string.IsNullOrEmpty(NameKZ))
            {
                sppstatuses = sppstatuses.Where(s => s.NameKZ.ToLower().Contains(NameKZ.ToLower()));
            }
            if (!string.IsNullOrEmpty(NameRU))
            {
                sppstatuses = sppstatuses.Where(s => s.NameRU.ToLower().Contains(NameRU.ToLower()));
            }

            switch (SortOrder)
            {
                case "NameEN":
                    sppstatuses = sppstatuses.OrderBy(s => s.NameEN);
                    break;
                case "NameENDesc":
                    sppstatuses = sppstatuses.OrderByDescending(s => s.NameEN);
                    break;
                case "NameKZ":
                    sppstatuses = sppstatuses.OrderBy(s => s.NameKZ);
                    break;
                case "NameKZDesc":
                    sppstatuses = sppstatuses.OrderByDescending(s => s.NameKZ);
                    break;
                case "NameRU":
                    sppstatuses = sppstatuses.OrderBy(s => s.NameRU);
                    break;
                case "NameRUDesc":
                    sppstatuses = sppstatuses.OrderByDescending(s => s.NameRU);
                    break;
                default:
                    sppstatuses = sppstatuses.OrderBy(s => s.Id);
                    break;
            }

            int PageSize = 50;
            int PageNumber = (Page ?? 1);

            return View(sppstatuses.ToPagedList(PageNumber, PageSize));
        }

        // GET: SPPStatuses/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SPPStatus sPPStatus = await db.SPPStatus.FindAsync(id);
            if (sPPStatus == null)
            {
                return HttpNotFound();
            }
            return View(sPPStatus);
        }

        // GET: SPPStatuses/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: SPPStatuses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create([Bind(Include = "Id,NameEN,NameKZ,NameRU")] SPPStatus sPPStatus)
        {
            if (ModelState.IsValid)
            {
                db.SPPStatus.Add(sPPStatus);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(sPPStatus);
        }

        // GET: SPPStatuses/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SPPStatus sPPStatus = await db.SPPStatus.FindAsync(id);
            if (sPPStatus == null)
            {
                return HttpNotFound();
            }
            return View(sPPStatus);
        }

        // POST: SPPStatuses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit([Bind(Include = "Id,NameEN,NameKZ,NameRU")] SPPStatus sPPStatus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sPPStatus).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(sPPStatus);
        }

        // GET: SPPStatuses/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SPPStatus sPPStatus = await db.SPPStatus.FindAsync(id);
            if (sPPStatus == null)
            {
                return HttpNotFound();
            }
            return View(sPPStatus);
        }

        // POST: SPPStatuses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            SPPStatus sPPStatus = await db.SPPStatus.FindAsync(id);
            db.SPPStatus.Remove(sPPStatus);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AtlasSolar/Views/SPPStatuses/Create.cshtml
@model AtlasSolar.Models.SPPStatus

@{
    ViewBag.Title = AtlasSolar.Resources.Common.Create;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@AtlasSolar.Resources.Common.Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@AtlasSolar.Resources.Common.SPPStatus</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NameEN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameEN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameEN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameKZ, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameKZ, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameKZ, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameRU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameRU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameRU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@AtlasSolar.Resources.Common.Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(AtlasSolar.Resources.Common.BackToList, "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AtlasSolar/Views/SPPStatuses/Delete.cshtml
@model AtlasSolar.Models.SPPStatus

@{
    ViewBag.Title = AtlasSolar.Resources.Common.Delete;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@AtlasSolar.Resources.Common.Delete</h2>

<h3>@AtlasSolar.Resources.Common.Delete?</h3>
<div>
    <h4>@AtlasSolar.Resources.Common.SPPStatus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NameEN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameEN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameKZ)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameKZ)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameRU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameRU)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="@AtlasSolar.Resources.Common.Delete" class="btn btn-default" /> |
            @Html.ActionLink(AtlasSolar.Resources.Common.BackToList, "Index")
        </div>
    }
</div>

AtlasSolar/Views/SPPStatuses/Details.cshtml
@model AtlasSolar.Models.SPPStatus

@{
    ViewBag.Title = AtlasSolar.Resources.Common.Details;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@AtlasSolar.Resources.Common.Details</h2>

<div>
    <h4>@AtlasSolar.Resources.Common.SPPStatus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NameEN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameEN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameKZ)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameKZ)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameRU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameRU)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink(AtlasSolar.Resources.Common.Edit, "Edit", new { id = Model.Id }) |
    @Html.ActionLink(AtlasSolar.Resources.Common.BackToList, "Index")
</p>

AtlasSolar/Views/SPPStatuses/Edit.cshtml
@model AtlasSolar.Models.SPPStatus

@{
    ViewBag.Title = AtlasSolar.Resources.Common.Edit;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@AtlasSolar.Resources.Common.Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@AtlasSolar.Resources.Common.SPPStatus</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.NameEN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameEN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameEN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameKZ, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameKZ, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameKZ, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameRU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameRU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameRU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@AtlasSolar.Resources.Common.Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(AtlasSolar.Resources.Common.BackToList, "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AtlasSolar/Views/SPPStatuses/Index.cshtml
@model PagedList.IPagedList<AtlasSolar.Models.SPPStatus>
@using PagedList.Mvc
<link href="~/Content/PagedList.css" rel="stylesheet" />

@{
    ViewBag.Title = AtlasSolar.Resources.Common.SPPStatuses;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@AtlasSolar.Resources.Common.SPPStatuses</h2>

<p>
    @Html.ActionLink(AtlasSolar.Resources.Common.Create, "Create")
</p>

@Html.PagedListPager(Model, Page => Url.Action("Index", new { Page, SortOrder = Request.QueryString["SortOrder"], NameEN = ViewBag.NameENFilter, NameKZ = ViewBag.NameKZFilter, NameRU = ViewBag.NameRUFilter }), new PagedListRenderOptions() { PageCountAndCurrentLocationFormat = "{0} / {1}", DisplayPageCountAndCurrentLocation = true })

@using (Html.BeginForm("Index", "SPPStatuses", new { SortOrder = Request.QueryString["SortOrder"], NameEN = ViewBag.NameENFilter, NameKZ = ViewBag.NameKZFilter, NameRU = ViewBag.NameRUFilter }, FormMethod.Get))
{
    @Html.Editor("SortOrder", null, new { htmlAttributes = new { @hidden = "hidden" }, value = Request.QueryString["SortOrder"] })
    <table class="table">
        <tr>
            <th>
                @Html.ActionLink(Html.DisplayNameFor(m => m.FirstOrDefault().NameEN).ToString(), "Index", new { SortOrder = ViewBag.NameENSort, NameEN = ViewBag.NameENFilter, NameKZ = ViewBag.NameKZFilter, NameRU = ViewBag.NameRUFilter })
                <br />
                @Html.Editor("NameEN", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
            </th>
            <th>
                @Html.ActionLink(Html.DisplayNameFor(m => m.FirstOrDefault().NameKZ).ToString(), "Index", new { SortOrder = ViewBag.NameKZSort, NameEN = ViewBag.NameKZFilter, NameKZ = ViewBag.NameKZFilter, NameRU = ViewBag.NameRUFilter })
                <br />
                @Html.Editor("NameKZ", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
            </th>
            <th>
                @Html.ActionLink(Html.DisplayNameFor(m => m.FirstOrDefault().NameRU).ToString(), "Index", new { SortOrder = ViewBag.NameRUSort, NameEN = ViewBag.NameRUFilter, NameKZ = ViewBag.NameKZFilter, NameRU = ViewBag.NameRUFilter })
                <br />
                @Html.Editor("NameRU", null, new { htmlAttributes = new { @class = "form-control" }, value = "" })
            </th>
            <th>
                <br />
                <input type="submit" value="@AtlasSolar.Resources.Common.Find" class="btn btn-default">
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NameEN)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NameKZ)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NameRU)
                </td>
                <td>
                    @Html.ActionLink(AtlasSolar.Resources.Common.Edit, "Edit", new { id = item.Id }) |
                    @Html.ActionLink(AtlasSolar.Resources.Common.Details, "Details", new { id = item.Id }) |
                    @Html.ActionLink(AtlasSolar.Resources.Common.Delete, "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
}

@Html.PagedListPager(Model, Page => Url.Action("Index", new { Page, SortOrder = Request.QueryString["SortOrder"], NameEN = ViewBag.NameENFilter, NameKZ = ViewBag.NameKZFilter, NameRU = ViewBag.NameRUFilter }), new PagedListRenderOptions() { PageCountAndCurrentLocationFormat = "{0} / {1}", DisplayPageCountAndCurrentLocation = true })